### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [swesterfeld/pandaresampler#1]
Nothing is installed by ```gmake install```.

**Comment by swesterfeld** [comment]
Right. My idea of how I thought a C++ developer would want to use this is by simply copying the stuff from lib/ into your C++ project (or use git submodule), using `-I<path_to_pandaresampler_lib>` and
```
#define PANDA_RESAMPLER_HEADER_ONLY
#include "pandaresampler.hh"
```
in your C++ source.  So I used autotools mainly for having a way to test the code, not as a means for installing it. I thought this would be useful for CLAP/VST plugins and similar cases, where you would want to keep the code self-contained anyway.

However, now that you submitted #1, #2 and #3, I am not sure if this is the only true way I should support. I might add two options:
1. I think I could easily install the headers in a system wide location, and users could still use the define to make the build self contained. This would avoid the burden of having to copy stuff to your build dir.
2. A static/shared library could be added for users who don't care about the extra dependency.

I'll think this through and make a new release.

**Comment by yurivict** [comment]
> Right. My idea of how I thought a C++ developer would want to use this is by simply copying the stuff from lib/ into your C++ project (or use git submodule), using -I<path_to_pandaresampler_lib> and [...]

But compiling by hand is not how compilation is done in most cases.
The software that would be using your library would get ported, which means that packages would be built from the port automatically, without any human interaction. The easiest way to port such depending software is to have a port/package for your library as well. And this requires it to have the "install" target.

**Comment by swesterfeld** [comment]
I've added support for `make install` to git master. So the next release will have that available.
